server:
  port: 8801

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://cdb-7erxhsui.cd.tencentcdb.com:10025
    username: root
    password: datamanage123456
    jpa:
      database: MySQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
